# use https://lint.travis-ci.org/ to check validity
# use https://gist.github.com/tgrrtt/96b206c22b82f92ce563 to see examples
# use https://github.com/travis-ci/artifacts#installation for artifacts guide
env:
  global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=mrl-bucket-02"
   - secure: "ZaIH9adJohSii+qyK9JL5FTiGUxttkzlAnxJxmGlR+xABntLD40gGryRJSvr/YqDfMQ9/eTQWqOsyxgr2eGpWV1/IhGzSo7regsT+TVZMYe3GRp5jJR/TlJGpzSaxYdMHPAa6EksSP6kxoGQElSSwqc8wOc5Piqml4/v2S4F7lg="
   - secure: "OKfavTeCuiDfSWp7KnJQ/RvnLkzNdxc0MvWG5osUi0bGDG5dhpYTxlgBJLr8jU/uVWBVzElms4Mrcl2Jku3K45ugG3M5M4QoMZWFbpPVTd13uZwsz4BTaMhgQbcrLMAh0QYsf4DywQu7dwBPmOszuOrsnXoI1ui/suuSDsF5sac="

language: java
sudo: false
script: ant dist
jdk:
- oraclejdk8

#before_script:
#  - gem install mime-types -v 2.6.2
#  - "gem install travis-artifacts"
   
#after_script:
#  - "travis-artifacts upload --path build/report --path report"   

# whitelist
# branches:
#   only:
#     - develop

# deploy:
#  provider: s3
#  deployment_group: s3 group
#  on:
    # experiment to 'always' deploy so the results of junit can always be seen
    # even if they fail
    # condition: true
#    all_branches: true
#  access_key_id: AKIAJGL6AEN37LDO3N7A
#  secret_access_key:
#    secure: W8HJgOUEt/d+C+1zeD+Znum0Yso8LLZ9eV8rUrYH2MIVl5dCcH+WaGwhLompNOAUbWYhjcr8Rn/SLqvCEcVWe651R4pwHiD0KNfDUwp907Ic/efluCd/T6RjCG7pjbE5bdPIeZjyupMcZMHU4aW7YN6QE1UlVPhDFKQlU84iGsc=
#  bucket: mrl-bucket-01
#  skip_cleanup: true
  # upload-dir: current
  # travis will only copy 1 dir
#  local_dir: dist
  # local_dir: build/report
#  acl: 'public_read'

addons:
  artifacts:
    bucket: mrl-bucket-02
    # key:
    #  secure: SyaIXy6OKDaYiew+...5vgAldy3jkmKA=
    # secret:
    #  secure: X19eaiiFZobD3uCk...X8cY+ohT8WkQ0=
    paths:
    # arbitrary shell commands are supported, but the output should be
    # converted to a ':'-delimited string.
    - $(ls build/report/*.xml | tr "\n" ":")
    # singular paths work fine, too
    - $HOME/build/lib/myrobotlab.jar  