# use https://lint.travis-ci.org/ to check validity
# use https://gist.github.com/tgrrtt/96b206c22b82f92ce563 to see examples
# use https://github.com/travis-ci/artifacts#installation for artifacts guide
# make the s3 directory public in aws give access to the artifacts

language: java
sudo: false
script: ant dist
jdk:
- oraclejdk8

deploy:
  provider: s3
  access_key_id: "AKIAJ6CQ5PPESWGSKNXA"
  secret_access_key: "Qs0Hh0yLdrqRn4PdkX+Agz3AVuaYANDuhYzwqHux/aJEp0WAu2cf4B/WECtf8AHAJMP9MpXGsRD3PnKNwQOqO93yjydLcFUhAhUJW9h9SfOsXmeLYO1ZO4dGHV4ODQtQdE92S8Amin/znK9PEl1tO8RYaTcxFfe71YbYHftPPVQ="
  bucket: "mrl-bucket-02"
  skip_cleanup: true
  upload-dir: "dist/current"
  region: "us-east-1"
